theme: jekyll-theme-minimal

title: Teste de software
description: PÃ¡gina da disciplina Teste de Software
show_downloads: false
lang: pt-BR
url: "https://teste-de-software.github.io"
github_repo: teste-de-software.github.io
github_username: leonardo-minora
